// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvqsxqfmajvaxmqxmtrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52cXN4cWZtYWp2YXhtcXhtdHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyODY5NDYsImV4cCI6MjA1Nzg2Mjk0Nn0.F-5DnaJnV83Bz_87YlrrI02OJGp5oQqT8s8S_zHbWrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);